In [10]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf
import numpy as np
np.set_printoptions(precision=3)

В библиотеке `TensorFlow` значения хранятся в массивах `NumPy`, и тензоры предоставляют ссылки на такие массивы.

In [11]:
a = np.array([1, 2, 3], dtype=np.int32)
b = [4, 5, 6]

In [12]:
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

In [13]:
print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


Чтобы получить доступ к значениям, на которые ссылается тензор, можно просто вызвать метод `.numpy()` не тензоре:

In [14]:
t_a.numpy()

array([1, 2, 3], dtype=int32)

In [15]:
t_b.numpy()

array([4, 5, 6], dtype=int32)

Тензор константных значений:

In [16]:
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)
print(const_tensor)

tf.Tensor([1.2   5.    3.142], shape=(3,), dtype=float32)


### Манипулирование с типом данных и формой тензора

In [20]:
print(t_a.dtype)

<dtype: 'int32'>


In [21]:
t_a_new = tf.cast(t_a, tf.int64)
print(t_a_new.dtype)

<dtype: 'int64'>


#### Транспонирование

In [23]:
t = tf.random.uniform(shape=(3, 5))
t

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0.132, 0.458, 0.052, 0.86 , 0.645],
       [0.286, 0.105, 0.627, 0.862, 0.067],
       [0.663, 0.568, 0.201, 0.28 , 0.268]], dtype=float32)>

In [24]:
t_tr = tf.transpose(t)
t_tr

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0.132, 0.286, 0.663],
       [0.458, 0.105, 0.568],
       [0.052, 0.627, 0.201],
       [0.86 , 0.862, 0.28 ],
       [0.645, 0.067, 0.268]], dtype=float32)>

In [25]:
print(t.shape, '-->', t_tr.shape)

(3, 5) --> (5, 3)


#### Изменение формы тензора

In [26]:
t = tf.zeros((30,))
t_reshape = tf.reshape(t, shape = (5, 6))
print(t_reshape.shape)

(5, 6)


#### Удаление измерений, имеющих размер 1, которые не нужны:

In [27]:
t = tf.zeros((1, 2, 1, 4, 1))
t_sqz = tf.squeeze(t, axis=(2, 4))
print(t.shape, '-->', t_sqz.shape)

(1, 2, 1, 4, 1) --> (1, 2, 4)


### Применение математических операций к тензорам

In [28]:
tf.random.set_seed(1)
t1 = tf.random.uniform(
    shape = (5, 2),
    minval=-1.0,
    maxval=1.0
)

t2 = tf.random.normal(
    shape=(5, 2),
    mean=0.0,
    stddev=1.0
)

In [29]:
t1

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.67 ,  0.803],
       [ 0.262, -0.131],
       [-0.416,  0.285],
       [ 0.952, -0.13 ],
       [ 0.32 ,  0.21 ]], dtype=float32)>

In [30]:
t2

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.403, -1.088],
       [-0.063,  1.337],
       [ 0.712, -0.489],
       [-0.764, -1.037],
       [-1.252,  0.021]], dtype=float32)>

#### Поэлементное произведение

In [31]:
t3 = tf.multiply(t1, t2).numpy()
print(t3)

[[-0.27  -0.874]
 [-0.017 -0.175]
 [-0.296 -0.139]
 [-0.727  0.135]
 [-0.401  0.004]]


#### Рассчет среднего, суммы и стандартного отклонения по определенной оси

In [43]:
# среднее
t4 = tf.reduce_mean(t1, axis=0)
print(t4.numpy())

[0.09  0.207]


In [42]:
# сумма
t4 = tf.reduce_sum(t1, axis=0)
print(t4.numpy())

[0.448 1.037]


In [41]:
# стандартное отклонение
t4 = tf.math.reduce_std(t1, axis=0)
print(t4.numpy())

[0.576 0.343]


In [40]:
t4 = tf.math.reduce_std(t1, axis=1)
print(t4.numpy())

[0.736 0.196 0.351 0.541 0.055]


#### Матричное произведение

In [45]:
print(t1.numpy())

[[-0.67   0.803]
 [ 0.262 -0.131]
 [-0.416  0.285]
 [ 0.952 -0.13 ]
 [ 0.32   0.21 ]]


In [46]:
print(t2.numpy())

[[ 0.403 -1.088]
 [-0.063  1.337]
 [ 0.712 -0.489]
 [-0.764 -1.037]
 [-1.252  0.021]]


In [44]:
t5 = tf.matmul(t1, t2, transpose_b=True)
print(t5.numpy())

[[-1.144  1.115 -0.87  -0.321  0.856]
 [ 0.248 -0.191  0.25  -0.064 -0.331]
 [-0.478  0.407 -0.436  0.022  0.527]
 [ 0.525 -0.234  0.741 -0.593 -1.194]
 [-0.099  0.26   0.125 -0.462 -0.396]]


In [50]:
t5 = tf.matmul(t1, t2, transpose_a=True)
print(t5.numpy())

[[-1.711  0.302]
 [ 0.371 -1.049]]


#### Рассчет нормы тензора

In [52]:
t6 = tf.norm(t1, ord=2, axis=1).numpy()
print(t6)

[1.046 0.293 0.504 0.96  0.383]


### Расщепление, укладывание стопкой и объединение тензоров

#### Расщепление

In [53]:
tf.random.set_seed(1)
t = tf.random.uniform((6,))
print(t.numpy())

[0.165 0.901 0.631 0.435 0.292 0.643]


In [58]:
t_splits = tf.split(t, num_or_size_splits=3)
type(t_splits)

list

In [59]:
[item.numpy() for item in t_splits]

[array([0.165, 0.901], dtype=float32),
 array([0.631, 0.435], dtype=float32),
 array([0.292, 0.643], dtype=float32)]

In [60]:
tf.random.set_seed(1)
t = tf.random.uniform((5,))
print(t.numpy())

[0.165 0.901 0.631 0.435 0.292]


In [62]:
# Укажем размеры отличающихся ращеплений:
t_splits = tf.split(t, num_or_size_splits=[3, 2])
[item.numpy() for item in t_splits]

[array([0.165, 0.901, 0.631], dtype=float32),
 array([0.435, 0.292], dtype=float32)]

#### Объединенме

In [68]:
A = tf.ones((3,))
B = tf.zeros((2,))
C = tf.concat([A, B], axis=0)
print(C.numpy())

[1. 1. 1. 0. 0.]


In [70]:
A = tf.ones((3,))
B = tf.zeros((3,))
C = tf.stack([A, B], axis=1)
print(C.numpy())

[[1. 0.]
 [1. 0.]
 [1. 0.]]
